{"created": 1740319570.904456, "duration": 0.0724799633026123, "exitcode": 1, "root": "/Users/tomhofkens/PycharmProjects/vbtoets", "environment": {}, "summary": {"passed": 1, "failed": 9, "total": 10, "collected": 10}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": ".", "type": "Dir"}]}, {"nodeid": "lib", "outcome": "passed", "result": []}, {"nodeid": "test_vraag01.py", "outcome": "passed", "result": [{"nodeid": "test_vraag01.py::test_vraag01_case1", "type": "Function", "lineno": 9}, {"nodeid": "test_vraag01.py::test_vraag01_case2", "type": "Function", "lineno": 12}, {"nodeid": "test_vraag01.py::test_vraag01_case3", "type": "Function", "lineno": 15}, {"nodeid": "test_vraag01.py::test_vraag01_case4", "type": "Function", "lineno": 18}, {"nodeid": "test_vraag01.py::test_vraag01_case5", "type": "Function", "lineno": 21}]}, {"nodeid": "test_vraag02.py", "outcome": "passed", "result": [{"nodeid": "test_vraag02.py::test_vraag02_case1", "type": "Function", "lineno": 9}, {"nodeid": "test_vraag02.py::test_vraag02_case2", "type": "Function", "lineno": 12}, {"nodeid": "test_vraag02.py::test_vraag02_case3", "type": "Function", "lineno": 17}]}, {"nodeid": "test_vraag04.py", "outcome": "passed", "result": [{"nodeid": "test_vraag04.py::test_vraag04", "type": "Function", "lineno": 12}]}, {"nodeid": "test_vraag05.py", "outcome": "passed", "result": [{"nodeid": "test_vraag05.py::test_vraag05", "type": "Function", "lineno": 9}]}, {"nodeid": ".", "outcome": "passed", "result": [{"nodeid": "lib", "type": "Dir"}, {"nodeid": "test_vraag01.py", "type": "Module"}, {"nodeid": "test_vraag02.py", "type": "Module"}, {"nodeid": "test_vraag04.py", "type": "Module"}, {"nodeid": "test_vraag05.py", "type": "Module"}]}], "tests": [{"nodeid": "test_vraag01.py::test_vraag01_case1", "lineno": 9, "outcome": "passed", "keywords": ["test_vraag01_case1", "test_vraag01.py", "vbtoets", ""], "setup": {"duration": 0.00018827500753104687, "outcome": "passed"}, "call": {"duration": 0.0186021410045214, "outcome": "passed"}, "teardown": {"duration": 0.00019656700897030532, "outcome": "passed"}}, {"nodeid": "test_vraag01.py::test_vraag01_case2", "lineno": 12, "outcome": "failed", "keywords": ["test_vraag01_case2", "test_vraag01.py", "vbtoets", ""], "setup": {"duration": 0.00013428500096779317, "outcome": "passed"}, "call": {"duration": 0.0003514030104270205, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 32, "message": "AssertionError"}, "traceback": [{"path": "test_vraag01.py", "lineno": 14, "message": "in test_vraag01_case2"}, {"path": "lib/utils.py", "lineno": 32, "message": "in check_exact_match"}], "stdout": "\n\n\u001b[91mE        De functie 'naar_links1([8, 2, 2, 0], 3)' geeft niet het verwachte resultaat.\u001b[0m\n\u001b[91mE        Verwacht: [8, 2, 2, 0]\u001b[0m\n\u001b[91mE        Gekregen: None\u001b[0m\n", "longrepr": "test_vraag01.py:14: in test_vraag01_case2\n    check_exact_match(vraag01, \"naar_links1\", ([8, 2, 2, 0], 3), [8, 2, 2, 0])\nlib/utils.py:32: in check_exact_match\n    assert False\nE   AssertionError"}, "teardown": {"duration": 0.00016825299826450646, "outcome": "passed"}}, {"nodeid": "test_vraag01.py::test_vraag01_case3", "lineno": 15, "outcome": "failed", "keywords": ["test_vraag01_case3", "test_vraag01.py", "vbtoets", ""], "setup": {"duration": 0.00012574499123729765, "outcome": "passed"}, "call": {"duration": 0.0002547309995861724, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 32, "message": "AssertionError"}, "traceback": [{"path": "test_vraag01.py", "lineno": 17, "message": "in test_vraag01_case3"}, {"path": "lib/utils.py", "lineno": 32, "message": "in check_exact_match"}], "stdout": "\n\n\u001b[91mE        De functie 'naar_links1([8, 2, 2, 0], 2)' geeft niet het verwachte resultaat.\u001b[0m\n\u001b[91mE        Verwacht: [8, 4, 0, 0]\u001b[0m\n\u001b[91mE        Gekregen: None\u001b[0m\n", "longrepr": "test_vraag01.py:17: in test_vraag01_case3\n    check_exact_match(vraag01, \"naar_links1\", ([8, 2, 2, 0], 2), [8, 4, 0, 0])\nlib/utils.py:32: in check_exact_match\n    assert False\nE   AssertionError"}, "teardown": {"duration": 0.00013136099732946604, "outcome": "passed"}}, {"nodeid": "test_vraag01.py::test_vraag01_case4", "lineno": 18, "outcome": "failed", "keywords": ["test_vraag01_case4", "test_vraag01.py", "vbtoets", ""], "setup": {"duration": 0.0001255930110346526, "outcome": "passed"}, "call": {"duration": 0.0002553240046836436, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 32, "message": "AssertionError"}, "traceback": [{"path": "test_vraag01.py", "lineno": 20, "message": "in test_vraag01_case4"}, {"path": "lib/utils.py", "lineno": 32, "message": "in check_exact_match"}], "stdout": "\n\n\u001b[91mE        De functie 'naar_links1([8, 0, 2, 0], 2)' geeft niet het verwachte resultaat.\u001b[0m\n\u001b[91mE        Verwacht: [8, 2, 0, 0]\u001b[0m\n\u001b[91mE        Gekregen: None\u001b[0m\n", "longrepr": "test_vraag01.py:20: in test_vraag01_case4\n    check_exact_match(vraag01, \"naar_links1\", ([8, 0, 2, 0], 2), [8, 2, 0, 0])\nlib/utils.py:32: in check_exact_match\n    assert False\nE   AssertionError"}, "teardown": {"duration": 0.00014518300304189324, "outcome": "passed"}}, {"nodeid": "test_vraag01.py::test_vraag01_case5", "lineno": 21, "outcome": "failed", "keywords": ["test_vraag01_case5", "test_vraag01.py", "vbtoets", ""], "setup": {"duration": 0.00012168800458312035, "outcome": "passed"}, "call": {"duration": 0.00023759300529491156, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 32, "message": "AssertionError"}, "traceback": [{"path": "test_vraag01.py", "lineno": 23, "message": "in test_vraag01_case5"}, {"path": "lib/utils.py", "lineno": 32, "message": "in check_exact_match"}], "stdout": "\n\n\u001b[91mE        De functie 'naar_links1([8, 2, 2, 0], 1)' geeft niet het verwachte resultaat.\u001b[0m\n\u001b[91mE        Verwacht: [8, 2, 2, 0]\u001b[0m\n\u001b[91mE        Gekregen: None\u001b[0m\n", "longrepr": "test_vraag01.py:23: in test_vraag01_case5\n    check_exact_match(vraag01, \"naar_links1\", ([8, 2, 2, 0], 1), [8, 2, 2, 0])\nlib/utils.py:32: in check_exact_match\n    assert False\nE   AssertionError"}, "teardown": {"duration": 0.00019940600031986833, "outcome": "passed"}}, {"nodeid": "test_vraag02.py::test_vraag02_case1", "lineno": 9, "outcome": "failed", "keywords": ["test_vraag02_case1", "test_vraag02.py", "vbtoets", ""], "setup": {"duration": 0.00015526398783549666, "outcome": "passed"}, "call": {"duration": 0.00014411199663300067, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 23, "message": "TypeError: C() takes 0 positional arguments but 2 were given"}, "traceback": [{"path": "test_vraag02.py", "lineno": 11, "message": "in test_vraag02_case1"}, {"path": "lib/utils.py", "lineno": 23, "message": "in check_exact_match"}], "longrepr": "test_vraag02.py:11: in test_vraag02_case1\n    check_exact_match(vraag02, \"C\", (0, 0), 1)\nlib/utils.py:23: in check_exact_match\n    result = function(*args)\nE   TypeError: C() takes 0 positional arguments but 2 were given"}, "teardown": {"duration": 0.00015265500405803323, "outcome": "passed"}}, {"nodeid": "test_vraag02.py::test_vraag02_case2", "lineno": 12, "outcome": "failed", "keywords": ["test_vraag02_case2", "test_vraag02.py", "vbtoets", ""], "setup": {"duration": 0.00011706700024660677, "outcome": "passed"}, "call": {"duration": 0.00017327100795228034, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 23, "message": "TypeError: C() takes 0 positional arguments but 2 were given"}, "traceback": [{"path": "test_vraag02.py", "lineno": 14, "message": "in test_vraag02_case2"}, {"path": "lib/utils.py", "lineno": 23, "message": "in check_exact_match"}], "longrepr": "test_vraag02.py:14: in test_vraag02_case2\n    check_exact_match(vraag02, \"C\", (1, 0), 1)\nlib/utils.py:23: in check_exact_match\n    result = function(*args)\nE   TypeError: C() takes 0 positional arguments but 2 were given"}, "teardown": {"duration": 0.00025988400739151984, "outcome": "passed"}}, {"nodeid": "test_vraag02.py::test_vraag02_case3", "lineno": 17, "outcome": "failed", "keywords": ["test_vraag02_case3", "test_vraag02.py", "vbtoets", ""], "setup": {"duration": 0.00012322499242145568, "outcome": "passed"}, "call": {"duration": 0.00014149799244478345, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 23, "message": "TypeError: C() takes 0 positional arguments but 2 were given"}, "traceback": [{"path": "test_vraag02.py", "lineno": 19, "message": "in test_vraag02_case3"}, {"path": "lib/utils.py", "lineno": 23, "message": "in check_exact_match"}], "longrepr": "test_vraag02.py:19: in test_vraag02_case3\n    check_exact_match(vraag02, \"C\", (1, 1), 1)\nlib/utils.py:23: in check_exact_match\n    result = function(*args)\nE   TypeError: C() takes 0 positional arguments but 2 were given"}, "teardown": {"duration": 0.00014591100625693798, "outcome": "passed"}}, {"nodeid": "test_vraag04.py::test_vraag04", "lineno": 12, "outcome": "failed", "keywords": ["test_vraag04", "test_vraag04.py", "vbtoets", ""], "setup": {"duration": 0.0001309789950028062, "outcome": "passed"}, "call": {"duration": 0.00028741799178533256, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 32, "message": "AssertionError"}, "traceback": [{"path": "test_vraag04.py", "lineno": 14, "message": "in test_vraag04"}, {"path": "lib/utils.py", "lineno": 32, "message": "in check_exact_match"}], "stdout": "\n\n\u001b[91mE        De functie 'integraal(<function f at 0x110ddc400>, 0, 1, 100)' geeft niet het verwachte resultaat.\u001b[0m\n\u001b[91mE        Verwacht: 0.33332500000000037\u001b[0m\n\u001b[91mE        Gekregen: 0.3283500000000004\u001b[0m\n", "longrepr": "test_vraag04.py:14: in test_vraag04\n    check_exact_match(vraag04, \"integraal\", (f, 0, 1, 100), 0.33332500000000037)\nlib/utils.py:32: in check_exact_match\n    assert False\nE   AssertionError"}, "teardown": {"duration": 0.00013084600504953414, "outcome": "passed"}}, {"nodeid": "test_vraag05.py::test_vraag05", "lineno": 9, "outcome": "failed", "keywords": ["test_vraag05", "test_vraag05.py", "vbtoets", ""], "setup": {"duration": 0.0001264019956579432, "outcome": "passed"}, "call": {"duration": 0.0001419809996150434, "outcome": "failed", "crash": {"path": "/Users/tomhofkens/PycharmProjects/vbtoets/lib/utils.py", "lineno": 55, "message": "TypeError: variantie() takes 0 positional arguments but 3 were given"}, "traceback": [{"path": "test_vraag05.py", "lineno": 11, "message": "in test_vraag05"}, {"path": "lib/utils.py", "lineno": 55, "message": "in check_approx_match"}], "longrepr": "test_vraag05.py:11: in test_vraag05\n    check_approx_match(vraag05, \"variantie\", ([1, 2, 3],[0.2, 0.5, 0.3],2.1), 0.49)\nlib/utils.py:55: in check_approx_match\n    result = function(*args)\nE   TypeError: variantie() takes 0 positional arguments but 3 were given"}, "teardown": {"duration": 0.0001609210012247786, "outcome": "passed"}}]}